books/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$',
        login_required(views.DashboardView.as_view()),
        name="dashboard"),

    # Organizations
    url(r'^organization/$',
        login_required(views.OrganizationListView.as_view()),
        name="organization-list"),
    url(r'^organization/selector/$',
        login_required(views.OrganizationSelectorView.as_view()),
        name="organization-selector"),
    url(r'^organization/create/$',
        login_required(views.OrganizationCreateView.as_view()),
        name="organization-create"),
    url(r'^organization/(?P<pk>\d+)/edit/$',
        login_required(views.OrganizationUpdateView.as_view()),
        name="organization-edit"),
    url(r'^organization/(?P<pk>\d+)/detail/$',
        login_required(views.OrganizationDetailView.as_view()),
        name="organization-detail"),
    url(r'^organization/(?P<pk>\d+)/select/$',
        login_required(views.OrganizationSelectionView.as_view()),
        name="organization-select"),

    # Tax Rates
    url(r'^tax_rates/$',
        login_required(views.TaxRateListView.as_view()),
        name="tax_rate-list"),
    url(r'^tax_rates/create/$',
        login_required(views.TaxRateCreateView.as_view()),
        name="tax_rate-create"),
    url(r'^tax_rates/(?P<pk>\d+)/edit/$',
        login_required(views.TaxRateUpdateView.as_view()),
        name="tax_rate-edit"),
    url(r'^tax_rates/(?P<pk>\d+)/delete/$',
        login_required(views.TaxRateDeleteView.as_view()),
        name="tax_rate-delete"),

    # Estimates
    url(r'^estimate/$',
        login_required(views.EstimateListView.as_view()),
        name="estimate-list"),
    url(r'^estimate/create/$',
        login_required(views.EstimateCreateView.as_view()),
        name="estimate-create"),
    url(r'^estimate/(?P<pk>\d+)/edit/$',
        login_required(views.EstimateUpdateView.as_view()),
        name="estimate-edit"),
    url(r'^estimate/(?P<pk>\d+)/delete/$',
        login_required(views.EstimateDeleteView.as_view()),
        name="estimate-delete"),
    url(r'^estimate/(?P<pk>\d+)/detail/$',
        login_required(views.EstimateDetailView.as_view()),
        name="estimate-detail"),

    # Invoices
    url(r'^invoice/$',
        login_required(views.InvoiceListView.as_view()),
        name="invoice-list"),
    url(r'^invoice/create/$',
        login_required(views.InvoiceCreateView.as_view()),
        name="invoice-create"),
    url(r'^invoice/(?P<pk>\d+)/edit/$',
        login_required(views.InvoiceUpdateView.as_view()),
        name="invoice-edit"),
    url(r'^invoice/(?P<pk>\d+)/delete/$',
        login_required(views.InvoiceDeleteView.as_view()),
        name="invoice-delete"),
    url(r'^invoice/(?P<pk>\d+)/detail/$',
        login_required(views.InvoiceDetailView.as_view()),
        name="invoice-detail"),

    # Bills
    url(r'^bill/$',
        login_required(views.BillListView.as_view()),
        name="bill-list"),
    url(r'^bill/create/$',
        login_required(views.BillCreateView.as_view()),
        name="bill-create"),
    url(r'^bill/(?P<pk>\d+)/edit/$',
        login_required(views.BillUpdateView.as_view()),
        name="bill-edit"),
    url(r'^bill/(?P<pk>\d+)/delete/$',
        login_required(views.BillDeleteView.as_view()),
        name="bill-delete"),
    url(r'^bill/(?P<pk>\d+)/detail/$',
        login_required(views.BillDetailView.as_view()),
        name="bill-detail"),

    # ExpenseClaims
    url(r'^expense-claim/$',
        login_required(views.ExpenseClaimListView.as_view()),
        name="expense_claim-list"),
    url(r'^expense-claim/create/$',
        login_required(views.ExpenseClaimCreateView.as_view()),
        name="expense_claim-create"),
    url(r'^expense-claim/(?P<pk>\d+)/edit/$',
        login_required(views.ExpenseClaimUpdateView.as_view()),
        name="expense_claim-edit"),
    url(r'^expense-claim/(?P<pk>\d+)/delete/$',
        login_required(views.ExpenseClaimDeleteView.as_view()),
        name="expense_claim-delete"),
    url(r'^expense-claim/(?P<pk>\d+)/detail/$',
        login_required(views.ExpenseClaimDetailView.as_view()),
        name="expense_claim-detail"),

    # Payments
    url(r'^payment/(?P<pk>\d+)/edit/$',
        login_required(views.PaymentUpdateView.as_view()),
        name="payment-edit"),
    url(r'^payment/(?P<pk>\d+)/delete/$',
        login_required(views.PaymentDeleteView.as_view()),
        name="payment-delete"),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from books import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logoutnlogin, name='logout'),
    url(r'^', include('connect.urls',
                      namespace="connect")),
    url(r'^books/', include('books.urls',
                            namespace="books")),
    url(r'^people/', include('people.urls',
                             namespace="people")),
    url(r'^reports/', include('reports.urls',
                              namespace="reports")),

    # third party
    url(r'^select2/', include('django_select2.urls')),
]

books/models.py
from decimal import Decimal as D
from datetime import date

from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.contenttypes.fields import (
    GenericForeignKey,
    GenericRelation)
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone

from libs import prices
from libs.checks import CheckingModelMixin
from libs.templatetags.currency_filters import currency_formatter
from libs.templatetags.format_filters import percentage_formatter
from .managers import (
    EstimateQuerySet,
    InvoiceQuerySet,
    BillQuerySet,
    ExpenseClaimQuerySet)

TWO_PLACES = D(10) ** -2


class Organization(models.Model):
    display_name = models.CharField(max_length=150,
        help_text="Name that you communicate")
    legal_name = models.CharField(max_length=150,
        help_text="Official name to appear on your reports, sales "
                  "invoices and bills")

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              related_name="owned_organizations")
    members = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name="organizations")

    class Meta:
        pass

    def __str__(self):
        return self.legal_name

    def get_absolute_url(self):
        return reverse('books:organization-detail', args=[self.pk])

    @property
    def turnover_excl_tax(self):
        return self.invoices.turnover_excl_tax() or D('0.00')

    @property
    def turnover_incl_tax(self):
        return self.invoices.turnover_incl_tax() or D('0.00')

    @property
    def debts_excl_tax(self):
        return self.bills.debts_excl_tax() or D('0.00')

    @property
    def debts_incl_tax(self):
        return self.bills.debts_incl_tax() or D('0.00')

    @property
    def profits(self):
        return self.turnover_excl_tax - self.debts_excl_tax

    @property
    def collected_tax(self):
        return self.turnover_incl_tax - self.turnover_excl_tax

    @property
    def deductible_tax(self):
        return self.debts_incl_tax - self.debts_excl_tax

    @property
    def tax_provisionning(self):
        return self.collected_tax - self.deductible_tax

    @property
    def overdue_total(self):
        due_invoices = self.invoices.dued()
        due_turnonver = due_invoices.turnover_incl_tax()
        total_paid = due_invoices.total_paid()
        return due_turnonver - total_paid


class TaxRate(models.Model):
    """
    Every transaction line item needs a Tax Rate.
    Tax Rates can have multiple Tax Components.

    For instance, you can have an item that is charged a Tax Rate
    called "City Import Tax (8%)" that has two components:
        - a city tax of 5%
        - an import tax of 3%.

    *inspired by Xero*
    """
    organization = models.ForeignKey('books.Organization',
                                     related_name="tax_rates",
                                     verbose_name="Attached to Organization")

    name = models.CharField(max_length=50)
    rate = models.DecimalField(max_digits=6,
                               decimal_places=5,
                               validators=[MinValueValidator(D('0')),
                                           MaxValueValidator(D('1'))])

    class Meta:
        pass

    def __str__(self):
        return "{} ({})".format(self.name, percentage_formatter(self.rate))


class AbstractSale(CheckingModelMixin, models.Model):
    number = models.IntegerField(default=1,
                                 db_index=True)

    # Total price needs to be stored with and wihtout taxes
    # because the tax percentage can vary depending on the associated lines
    total_incl_tax = models.DecimalField("Total (inc. tax)",
                                         decimal_places=2,
                                         max_digits=12,
                                         default=D('0'))
    total_excl_tax = models.DecimalField("Total (excl. tax)",
                                         decimal_places=2,
                                         max_digits=12,
                                         default=D('0'))

    # tracking
    date_issued = models.DateField(default=date.today)
    date_dued = models.DateField("Due date",
                                 blank=True, null=True,
                                 help_text="The date when the total amount "
                                           "should have been collected")
    date_paid = models.DateField(blank=True, null=True)

    class Meta:
        abstract = True

    class CheckingOptions:
        fields = (
            'total_incl_tax',
            'total_excl_tax',
            'date_dued',
        )

    def __str__(self):
        return "#{} ({})".format(self.number, self.total_incl_tax)

    def get_detail_url(self):
        raise NotImplementedError

    def get_edit_url(self):
        raise NotImplementedError

    def compute_totals(self):
        self.total_excl_tax = self.get_total_excl_tax()
        self.total_incl_tax = self.get_total_incl_tax()

    def _get_total(self, prop):
        """
        For executing a named method on each line of the basket
        and returning the total.
        """
        total = D('0.00')
        line_queryset = self.lines.all()
        for line in line_queryset:
            total = total + getattr(line, prop)
        return total

    @property
    def total_tax(self):
        return self.total_incl_tax - self.total_excl_tax

    def get_total_excl_tax(self):
        return self._get_total('line_price_excl_tax')

    def get_total_incl_tax(self):
        return self._get_total('line_price_incl_tax')

    @property
    def total_paid(self):
        total = D('0')
        for p in self.payments.all():
            total += p.amount
        return total

    @property
    def total_due_incl_tax(self):
        due = self.total_incl_tax
        due -= self.total_paid
        return due

    def is_fully_paid(self):
        paid = self.total_paid.quantize(TWO_PLACES)
        total = self.total_incl_tax.quantize(TWO_PLACES)
        return paid >= total

    def is_partially_paid(self):
        paid = self.total_paid.quantize(TWO_PLACES)
        total = self.total_incl_tax.quantize(TWO_PLACES)
        return paid and paid > 0 and paid < total

    @property
    def payroll_taxes(self):
        # TODO implement collected/accurial
        paid = self.total_paid
        payroll = D('0')
        for emp in self.organization.employees.all():
            if not emp.salary_follows_profits:
                continue
            payroll += paid * emp.shares_percentage * emp.payroll_tax_rate
        return payroll

    def _check_total(self, check, total, computed_total):
        if total.quantize(TWO_PLACES) != computed_total.quantize(TWO_PLACES):
            check.mark_fail(level=check.LEVEL_ERROR,
                            message="The computed amount isn't correct, it "
                                    "should be {}, please edit and save the "
                                    "{} to fix it.".format(
                                        currency_formatter(total),
                                        self._meta.verbose_name))
        else:
            check.mark_pass()
        return check

    def check_total_excl_tax(self, check):
        total = self.get_total_excl_tax()
        return self._check_total(check, total, self.total_excl_tax)

    def check_total_incl_tax(self, check):
        total = self.get_total_incl_tax()
        return self._check_total(check, total, self.total_incl_tax)

    def check_date_dued(self, check):
        if self.date_dued is None:
            check.mark_fail(message="No due date specified")
            return check

        if self.total_excl_tax == D('0'):
            check.mark_fail(message="The invoice has no value")
            return check

        if self.is_fully_paid():
            last_payment = self.payments.all().first()
            formatted_date = last_payment.date_paid.strftime('%B %d, %Y')
            check.mark_pass(message="Has been paid on the {}"
                .format(formatted_date))
            return check

        if timezone.now().date() > self.date_dued:
            check.mark_fail(message="The due date has been exceeded.")
        else:
            check.mark_pass()
        return check


class AbstractSaleLine(models.Model):
    label = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    unit_price_excl_tax = models.DecimalField(max_digits=8,
                                              decimal_places=2)
    quantity = models.DecimalField(max_digits=8,
                                   decimal_places=2,
                                   default=1)

    class Meta:
        abstract = True

    def __str__(self):
        return self.label

    @property
    def unit_price(self):
        """Returns the `Price` instance representing the instance"""
        unit = self.unit_price_excl_tax
        tax = unit * self.tax_rate.rate
        p = prices.Price(settings.ACCOUNTING_DEFAULT_CURRENCY, unit, tax=tax)
        return p

    @property
    def line_price_excl_tax(self):
        return self.quantity * self.unit_price.excl_tax

    @property
    def line_price_incl_tax(self):
        return self.quantity * self.unit_price.incl_tax

    @property
    def taxes(self):
        return self.line_price_incl_tax - self.line_price_excl_tax

    def from_client(self):
        raise NotImplementedError

    def to_client(self):
        raise NotImplementedError


class Estimate(AbstractSale):
    organization = models.ForeignKey('books.Organization',
                                     related_name="estimates",
                                     verbose_name="From Organization")
    client = models.ForeignKey('people.Client',

templates/books/bill_create_or_update.html
{% extends "layout.html" %}
{% load static bootstrap3 introspection_filters widget_tweaks %}

{% block head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="page-header">Create a {{ form|get_form_model_verbose_name }}</h1>

    <form action="." method="post" class="form">
        {% csrf_token %}

        <div class="row">
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_number">Number:</label>
                {% if form.name.value %}
                <input type="number" name="number" maxlength="256" value="{{form.number.value}}" class="form-control {% if form.number.errors %}is-invalid{% else%}is-valid{% endif %}"
                    required id="id_number" />
                {% else %}
                    {{ form.number|add_class:"form-control" }}
                {% endif %}
                <div class="invalid-feedback">{{ form.number.errors }}</div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_client">Client:</label>
                <select class="form-control" id="id_client" name="client">
                    {% if form.client.value %}
                        <option value="{{ form.client.value }}">{{ form.client.value }}</option>
                    {% else %}
                        <option value="" selected>-</option>
                    {% endif %}
                    {% for client in view.clients %}
                        <option value="{{client.id}}">{{client.name}}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback">{{ form.client.errors }}</div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_date_issued">Date Issued:</label>
                <div id="filterDate2">
                    <div class="input-group date" id="id_date_issued" data-date-format="dd.mm.yyyy">
                        <input type="text" name="date_issued" id="id_date_issued" class="form-control" value="">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_date_dued">Due Date:</label>
                <div id="filterDate2">
                    <div class="input-group date" id="id_date_dued" data-date-format="dd.mm.yyyy">
                        <input type="text" name="date_dued" autocomplete="off" id="id_date_dued" class="form-control" value="">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                </div>
                {% if form.date_dued.help_text %}
                <small class="form-text text-muted">
                    {{ form.date_dued.help_text }}
                </small>
                {% endif %}
            </div>
        </div>

        <h2 class="page-header">Content</h2>
        {{ line_formset.management_form }}
        {{ line_formset.non_field_errors }}
        <table class="table table-striped table-bordered">
            <thead>
                <th>#</th>
                <th>Label</th>
                <th>Description</th>
                <th>Unit (excl. tax)</th>
                <th>Qt.</th>
                <th>Tax rate</th>
                <th>Total</th>
            </thead>
            <tbody>
            {% for line_form in line_formset %}
                <tr class="formset-form">
                    <td class="col-md-0 counter">
                        {{ forloop.counter }}
                        {{ line_form.id }}
                    </td>
                    <td class="col-md-2">
                        {% bootstrap_field line_form.label show_label=False %}
                    </td>
                    <td class="col-md-4">
                        {% bootstrap_field line_form.description show_label=False %}
                    </td>
                    <td class="col-md-2">
                        {% bootstrap_field line_form.unit_price_excl_tax show_label=False %}
                    </td>
                    <td class="col-md-1">
                        {% bootstrap_field line_form.quantity show_label=False %}
                    </td>
                    <td class="col-md-1">
                        {% bootstrap_field line_form.tax_rate show_label=False %}
                    </td>
                    <td>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% buttons layout='vertical' %}
            <button type="submit" class="btn btn-success">
                {% bootstrap_icon "star" %} Create
            </button>
        {% endbuttons %}
    </form>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/books/invoice_or_bill_create.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_client').select2();
        });

        $('#id_date_issued').datepicker({
            format: "yyyy-mm-dd",
            todayBtn: true,
            orientation: "bottom left",
            autoclose: true,
            todayHighlight: true
        }).datepicker('setDate', 'today');
        $('#id_date_dued').datepicker({
            format: "yyyy-mm-dd",
            todayBtn: true,
            orientation: "bottom left",
            autoclose: true,
            todayHighlight: true
        });
    </script>
{% endblock %}

templates/books/bill_detail.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
    {{ block.super }}

    {# NB: because the payment form is a subform it won't output the correct assets, so we explicitly put it there #}
    <link rel="stylesheet" href="{% static 'css/datetimepicker.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>

    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="page-header">
        Bill #{{ bill.number }} <small>/ detail</small>
        <div class="btn-group pull-right">
            <a href="{% url 'books:bill-edit' bill.pk %}" class="btn btn-default" role="button">Edit</a>
            <a href="{% url 'books:bill-delete' bill.pk %}" class="btn btn-danger" role="button">Supprimer</a>
        </div>
    </h1>

    {% include "books/_generics/sale_detail.html" with object=bill lines=lines payments=bill.payments.all form=form %}

{% endblock content %}

templates/books/estimate_create_or_update.html
{% extends "layout.html" %}
{% load static bootstrap3 introspection_filters widget_tweaks %}

{% block head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="page-header">Create a {{ form|get_form_model_verbose_name }}</h1>

    <form action="." method="post" class="form">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_number">Number:</label>
                {% if form.number.value %}
                    <input type="number" name="number" maxlength="256" value="{{form.number.value}}" class="form-control {% if form.number.errors %}is-invalid{% else%}is-valid{% endif %}"
                    required id="id_number" />
                {% else %}
                    {{ form.number|add_class:"form-control" }}
                {% endif %}
                <div class="invalid-feedback">{{ form.number.errors }}</div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_client">Client:</label>
                <select class="form-control" id="id_client" name="client">
                    {% if form.client.value %}
                        <option value="{{ form.client.value }}">{{ form.client.value }}</option>
                    {% else %}
                        <option value="" selected>-</option>
                    {% endif %}
                    {% for client in view.clients %}
                        <option value="{{client.id}}">{{client.name}}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback">{{ form.client.errors }}</div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_date_issued">Date Issued:</label>
                <div id="filterDate2">
                    <div class="input-group date"id="id_date_issued" data-date-format="dd.mm.yyyy">
                        <input type="text" name="date_issued" id="id_date_issued" class="form-control" value="">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group col-sm-12 col-md-12">
                <label for="id_date_dued">Due Date:</label>
                <div id="filterDate2">
                    <div class="input-group date" id="id_date_dued" data-date-format="dd.mm.yyyy">
                        <input type="text" name="date_dued"autocomplete="off" id="id_date_dued" class="form-control" value="">
                        <div class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </div>
                    </div>
                </div>
                {% if form.date_dued.help_text %}
                    <small class="form-text text-muted">
                        {{ form.date_dued.help_text }}
                    </small>
                {% endif %}
            </div>
            <!-- {% include 'includes/form.html' with form=form %} -->
        </div>
        <h2 class="page-header">Content</h2>
        {{ line_formset.management_form }}
        {{ line_formset.non_field_errors }}
        <table class="table table-striped table-bordered">
            <thead>
                <th>#</th>
                <th>Label</th>
                <th>Description</th>
                <th>Unit (excl. tax)</th>
                <th>Qt.</th>
                <th>Tax rate</th>
                <th>Total</th>
            </thead>
            <tbody>
            {% for line_form in line_formset %}
                <tr class="formset-form">
                    <td class="col-md-0 counter">
                        {{ forloop.counter }}
                        {{ line_form.id }}
                    </td>
                    <td class="col-md-2">
                        {% bootstrap_field line_form.label show_label=False %}
                    </td>
                    <td class="col-md-4">
                        {% bootstrap_field line_form.description show_label=False %}
                    </td>
                    <td class="col-md-2">
                        {% bootstrap_field line_form.unit_price_excl_tax show_label=False %}
                    </td>
                    <td class="col-md-1">
                        {% bootstrap_field line_form.quantity show_label=False %}
                    </td>
                    <td class="col-md-1">
                        {% bootstrap_field line_form.tax_rate show_label=False %}
                    </td>
                    <td></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        {% buttons layout='vertical' %}
            <button type="submit" class="btn btn-success">
                {% bootstrap_icon "star" %} Create
            </button>
        {% endbuttons %}
    </form>
{% endblock content %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script src="{% static 'js/books/invoice_or_bill_create.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
                $('#id_client').select2();
            });
        
        $('#id_date_issued').datepicker({
            format: "yyyy-mm-dd",
            todayBtn: true,
            orientation: "bottom left",
            autoclose: true,
            todayHighlight: true
        }).datepicker('setDate', 'today');
        $('#id_date_dued').datepicker({
            format: "yyyy-mm-dd",
            todayBtn: true,
            orientation: "bottom left",
            autoclose: true,
            todayHighlight: true
        });
    </script>
{% endblock %}

templates/books/expense_claim_detail.html
{% extends "layout.html" %}
{% load static %}

{% block head %}
    {{ block.super }}

    {# NB: because the payment form is a subform it won't output the correct assets, so we explicitly put it there #}
    <link rel="stylesheet" href="{% static 'css/datetimepicker.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>

    {{ form.media }}
{% endblock %}

{% block content %}
    <h1 class="page-header">
        Expense claim #{{ expense_claim.number }} <small>/ detail</small>
        <div class="btn-group pull-right">
            <a href="{% url 'books:expense_claim-edit' expense_claim.pk %}" class="btn btn-default" role="button">Edit</a>
            <a href="{% url 'books:expense_claim-delete' expense_claim.pk %}" class="btn btn-danger" role="button">Supprimer</a>
        </div>
    </h1>

    {% include "books/_generics/sale_detail.html" with object=expense_claim lines=lines payments=expense_claim.payments.all form=form %}

{% endblock content %}

templates/books/organization_detail.html
{% extends "layout.html" %}
{% load currency_filters %}

{% block content %}
    <h1 class="page-header">
        {{ organization.display_name }} <small>/ organization detail</small>
        <div class="btn-group pull-right">
            <a href="{% url 'books:organization-edit' organization.pk %}" class="btn btn-default" role="button">Edit</a>
        </div>
    </h1>

    <div class="row placeholders">
        <div class="col-xs-6 col-sm-3">
            <div class="figure">
                <h4>{{ organization.turnover_excl_tax|currency|default:"-" }}</h4>
                <span class="text-muted">Turnover</span>
            </div>
        </div>
        <div class="col-xs-6 col-sm-3">
            <div class="figure">
                <h4>{{ organization.profits|currency|default:"-" }}</h4>
                <span class="text-muted">Profits</span>
            </div>
        </div>
        <div class="col-xs-6 col-sm-3">
            <div class="figure">
                <h4>{{ organization.tax_provisionning|currency|default:0 }}</h4>
                <span class="text-muted">Tax Provisionning</span>
            </div>
        </div>
        <div class="col-xs-6 col-sm-3">
            <div class="figure">
                <h4>{{ organization.overdue_total|currency|default:0 }}</h4>
                <span class="text-muted">Due payments</span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6">
            {% include "books/invoice_list.html" with invoices=invoices hide_edit=True %}
            <a href="{% url 'books:invoice-create' %}" class="btn btn-primary btn-lg" role="button">
                Add an invoice
            </a>
        </div>
        <div class="col-xs-12 col-sm-6">
            {% include "books/bill_list.html" with bills=bills hide_edit=True %}
            <a href="{% url 'books:bill-create' %}" class="btn btn-primary btn-lg" role="button">
                Add an bill
            </a>
        </div>
    </div>
{% endblock content %}

templates/books/tax_rate_create_or_update.html
{% extends "_generics/form.html" %}