books/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views


urlpatterns = [
    url(r'^$',
        login_required(views.DashboardView.as_view()),
        name="dashboard"),

    # Organizations
    url(r'^organization/$',
        login_required(views.OrganizationListView.as_view()),
        name="organization-list"),
    url(r'^organization/selector/$',
        login_required(views.OrganizationSelectorView.as_view()),
        name="organization-selector"),
    url(r'^organization/create/$',
        login_required(views.OrganizationCreateView.as_view()),
        name="organization-create"),
    url(r'^organization/(?P<pk>\d+)/edit/$',
        login_required(views.OrganizationUpdateView.as_view()),
        name="organization-edit"),
    url(r'^organization/(?P<pk>\d+)/detail/$',
        login_required(views.OrganizationDetailView.as_view()),
        name="organization-detail"),
    url(r'^organization/(?P<pk>\d+)/select/$',
        login_required(views.OrganizationSelectionView.as_view()),
        name="organization-select"),

    # Tax Rates
    url(r'^tax_rates/$',
        login_required(views.TaxRateListView.as_view()),
        name="tax_rate-list"),
    url(r'^tax_rates/create/$',
        login_required(views.TaxRateCreateView.as_view()),
        name="tax_rate-create"),
    url(r'^tax_rates/(?P<pk>\d+)/edit/$',
        login_required(views.TaxRateUpdateView.as_view()),
        name="tax_rate-edit"),
    url(r'^tax_rates/(?P<pk>\d+)/delete/$',
        login_required(views.TaxRateDeleteView.as_view()),
        name="tax_rate-delete"),

    # Estimates
    url(r'^estimate/$',
        login_required(views.EstimateListView.as_view()),
        name="estimate-list"),
    url(r'^estimate/create/$',
        login_required(views.EstimateCreateView.as_view()),
        name="estimate-create"),
    url(r'^estimate/(?P<pk>\d+)/edit/$',
        login_required(views.EstimateUpdateView.as_view()),
        name="estimate-edit"),
    url(r'^estimate/(?P<pk>\d+)/delete/$',
        login_required(views.EstimateDeleteView.as_view()),
        name="estimate-delete"),
    url(r'^estimate/(?P<pk>\d+)/detail/$',
        login_required(views.EstimateDetailView.as_view()),
        name="estimate-detail"),

    # Invoices
    url(r'^invoice/$',
        login_required(views.InvoiceListView.as_view()),
        name="invoice-list"),
    url(r'^invoice/create/$',
        login_required(views.InvoiceCreateView.as_view()),
        name="invoice-create"),
    url(r'^invoice/(?P<pk>\d+)/edit/$',
        login_required(views.InvoiceUpdateView.as_view()),
        name="invoice-edit"),
    url(r'^invoice/(?P<pk>\d+)/delete/$',
        login_required(views.InvoiceDeleteView.as_view()),
        name="invoice-delete"),
    url(r'^invoice/(?P<pk>\d+)/detail/$',
        login_required(views.InvoiceDetailView.as_view()),
        name="invoice-detail"),

    # Bills
    url(r'^bill/$',
        login_required(views.BillListView.as_view()),
        name="bill-list"),
    url(r'^bill/create/$',
        login_required(views.BillCreateView.as_view()),
        name="bill-create"),
    url(r'^bill/(?P<pk>\d+)/edit/$',
        login_required(views.BillUpdateView.as_view()),
        name="bill-edit"),
    url(r'^bill/(?P<pk>\d+)/delete/$',
        login_required(views.BillDeleteView.as_view()),
        name="bill-delete"),
    url(r'^bill/(?P<pk>\d+)/detail/$',
        login_required(views.BillDetailView.as_view()),
        name="bill-detail"),

    # ExpenseClaims
    url(r'^expense-claim/$',
        login_required(views.ExpenseClaimListView.as_view()),
        name="expense_claim-list"),
    url(r'^expense-claim/create/$',
        login_required(views.ExpenseClaimCreateView.as_view()),
        name="expense_claim-create"),
    url(r'^expense-claim/(?P<pk>\d+)/edit/$',
        login_required(views.ExpenseClaimUpdateView.as_view()),
        name="expense_claim-edit"),
    url(r'^expense-claim/(?P<pk>\d+)/delete/$',
        login_required(views.ExpenseClaimDeleteView.as_view()),
        name="expense_claim-delete"),
    url(r'^expense-claim/(?P<pk>\d+)/detail/$',
        login_required(views.ExpenseClaimDetailView.as_view()),
        name="expense_claim-detail"),

    # Payments
    url(r'^payment/(?P<pk>\d+)/edit/$',
        login_required(views.PaymentUpdateView.as_view()),
        name="payment-edit"),
    url(r'^payment/(?P<pk>\d+)/delete/$',
        login_required(views.PaymentDeleteView.as_view()),
        name="payment-delete"),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from books import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', views.logoutnlogin, name='logout'),
    url(r'^', include('connect.urls',
                      namespace="connect")),
    url(r'^books/', include('books.urls',
                            namespace="books")),
    url(r'^people/', include('people.urls',
                             namespace="people")),
    url(r'^reports/', include('reports.urls',
                              namespace="reports")),

    # third party
    url(r'^select2/', include('django_select2.urls')),
]

connect/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$',
        views.RootRedirectionView.as_view(),
        name="root"),

    # Step by step
    url(r'^getting-started/$',
        views.GettingStartedView.as_view(),
        name="getting-started")
]

people/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Clients
    url(r'^client/$',
        views.ClientListView.as_view(),
        name="client-list"),
    url(r'^client/create/$',
        views.ClientCreateView.as_view(),
        name="client-create"),
    url(r'^client/(?P<pk>\d+)/edit/$',
        views.ClientUpdateView.as_view(),
        name="client-edit"),
    url(r'^client/(?P<pk>\d+)/detail/$',
        views.ClientDetailView.as_view(),
        name="client-detail"),

    # Employees
    url(r'^employee/$',
        views.EmployeeListView.as_view(),
        name="employee-list"),
    url(r'^employee/create/$',
        views.EmployeeCreateView.as_view(),
        name="employee-create"),
    url(r'^employee/(?P<pk>\d+)/edit/$',
        views.EmployeeUpdateView.as_view(),
        name="employee-edit"),
    url(r'^employee/(?P<pk>\d+)/detail/$',
        views.EmployeeDetailView.as_view(),
        name="employee-detail"),
]

reports/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Reports
    url(r'^report/$',
        views.ReportListView.as_view(),
        name="report-list"),
    url(r'^report/tax/$',
        views.TaxReportView.as_view(),
        name="tax-report"),
    url(r'^report/profitloss/$',
        views.ProfitAndLossReportView.as_view(),
        name="profit-and-loss-report"),
    url(r'^report/payrun/$',
        views.PayRunReportView.as_view(),
        name="pay-run-report"),
    url(r'^report/invoicedetails/$',
        views.InvoiceDetailsView.as_view(),
        name="invoice-details-report"),

    # Settings
    url(r'^settings/$',
        views.SettingsListView.as_view(),
        name="settings-list"),
    url(r'^settings/business/$',
        views.BusinessSettingsUpdateView.as_view(),
        name="settings-business"),
    url(r'^settings/financial/$',
        views.FinancialSettingsUpdateView.as_view(),
        name="settings-financial"),
    url(r'^settings/payrun/$',
        views.PayRunSettingsUpdateView.as_view(),
        name="settings-payrun"),
]

templates/base.html
{% load static %}<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html style="height: auto; min-height: 100%;"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Beta | Accounting</title>
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.css' %}">
        <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/Admin.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/all-skins.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
        <link rel="stylesheet" href="{% static 'font-awesome-4.7.0\css\font-awesome.min.css' %}">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <style type="text/css">
            .jqstooltip {
                position: absolute;
                left: 0px;
                top: 0px;
                visibility: hidden;
                background: rgb(0, 0, 0) transparent;
                background-color: rgba(0, 0, 0, 0.6);
                filter: progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);
                -ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";
                color: white;
                font: 10px arial, san serif;
                text-align: left;
                white-space: nowrap;
                padding: 5px;
                border: 1px solid white;
                box-sizing: content-box;
                z-index: 10000;
            }
        
            .jqsfield {
                color: white;
                font: 10px arial, san serif;
                text-align: left;
            }
        </style>
        <style>
            @import url(http://fonts.googleapis.com/css?family=Bree+Serif);
            body {
                font-family: 'Helvetica Neue', sans-serif;
            }
            h1, h2, h3, h4, h5, h6{
                font-family: 'Bree Serif', serif;
            }
        </style>

        <!-- Custom styles for this template -->
        

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'js/modernizr.js' %}"></script>

        {% block head %}{% endblock %}
    </head>
    <body class="skin-blue sidebar-mini wysihtml5-supported" style="height: 800; min-height: 100%;">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block maincontent %}{% endblock %}

        {% block scripts %}
            <script src="{% static 'js/jquery.min.js' %}"></script>
            <script src="{% static 'js/select2.min.js' %}"></script>
            <script src="{% static 'js/bootstrap.min.js' %}"></script>
            <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
            <script src="{% static 'js/main.js' %}"></script>
            <script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>
            <script src="{% static 'js/fastclick.js' %}"></script>
            <script src="{% static 'js/admin.min.js' %}"></script>
            <script src="{% static 'js/dataTables.bootstrap.min.js' %}"></script>
            <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#datatable').DataTable();
                });
            </script>
        {% endblock %}
    </body>
</html>

templates/layout.html
{% extends "base.html" %}
{% load nav bootstrap3 %}

{% block maincontent %}
    {% block nav %}
    <div class="wrapper" style="height: auto; min-height: 100%;">
    
        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">
                    <b>BETA</b>
                </span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg">
                    <b>BETA</b>ccounting</span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
    
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- Messages: style can be found in dropdown.less-->
                        {% if user.is_authenticated %}
                            <li class="dropdown navbar-right" style="margin-right:3px;">
                                <a class="dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    {{ user.username }} <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="#">My account</a></li>
                                    <li><a class="dropdown-item" href="#">Change password</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                                </ul>
                            </li>
                        {% endif %}
                        {% url 'connect:getting-started' as getting_started_url %}
                        <li class="navbar-nav navbar-right" style="margin-right:0px;">
                            <a href="{{ getting_started_url }}">
                                <span>Getting started</span>
                            </a>
                        </li>
                        <!-- Notifications: style can be found in dropdown.less -->
    
                        <!-- Tasks: style can be found in dropdown.less -->
    
                        <!-- User Account: style can be found in dropdown.less -->
    
                        <!-- Control Sidebar Toggle Button -->
    
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar" style="height: auto;">
                <!-- Sidebar user panel -->
    
                <!-- search form -->
    
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu tree tab-menu" data-widget="tree">
                    {% url 'books:dashboard' as books_dashboard_url %}
                    <li class="{% if active_tab == 'dashboard' %} active{% endif %}">
                        <a href="{{ books_dashboard_url }}">
                            <i class="fa fa-home"></i>
                            <span>Overview</span>
                        </a>
                    </li>
                    <li class="header">Accounting</li>
                    {% url 'books:estimate-list' as books_estimate_list_url %}
                    {% url 'books:invoice-list' as books_invoice_list_url %}
                    {% url 'books:bill-list' as books_bill_list_url %}
                    {% url 'books:expense_claim-list' as books_exepense_claim_list_url %}
                    {% url 'books:tax_rate-list' as books_tax_rate_list_url %}
                    <li class="{% if active_tab == 'estimate-list' %} active{% endif %}">
                        <a href="{{ books_estimate_list_url }}">
                            <i class="fa fa-files-o"></i>
                            <span>Estimates</span>
                        </a>
                    </li>
                    <li class="{% if active_tab == 'invoice-list' %} active{% endif %}">
                        <a href="{{ books_invoice_list_url }}">
                            <i class="fa fa-file"></i>
                            <span>Invoice</span>
                        </a>
                    </li>
                    <li class="{% if active_tab == 'bill-list' %} active{% endif %}">
                        <a href="{{ books_bill_list_url }}">
                            <i class="fa fa-newspaper-o"></i>
                            <span>Bills</span>
                        </a>
                    </li>
                    <li class="{% if active_tab == 'expense_claim-list' %} active{% endif %}">
                        <a href="{{ books_exepense_claim_list_url }}">
                            <i class="fa fa-inr fa-lg"></i>
                            <span>Expense Claims</span>
                        </a>
                    </li>
                    <li class="{% if active_tab == 'tax_rate-list' %} active{% endif %}">
                        <a href="{{ books_tax_rate_list_url }}">
                            <i class="fa fa-money"></i>
                            <span>Tax Rates</span>
                        </a>
                    </li>
                    <li class="header">People</li>
                    {% url 'people:client-list' as clients_client_list_url %}
                    {% url 'people:employee-list' as employees_employee_list_url %}
                    <li class="{% if active_tab == 'client-list' %} active{% endif %}">
                        <a href="{{ clients_client_list_url }}">
                            <i class="fa fa-users"></i>
                            <span>Clients</span>
                        </a>
                    </li>
                    <li class="{% if active_tab == 'employee-list' %} active{% endif %}">
                        <a href="{{ employees_employee_list_url }}">
                            <i class="fa fa-user"></i>
                            <span>Employees</span>
                        </a>
                    </li>
                    <li class="header">Settings</li>
                    {% url 'reports:report-list' as reports_report_list_url %}
                    <li class="{% if active_tab == 'report-list' %} active{% endif %}">
                        <a href="{{ reports_report_list_url }}">
                            <i class="fa fa-send"></i>
                            <span>Reports</span>
                        </a>
                    </li>
                    {% url 'reports:settings-list' as reports_settings_list_url %}
                    <li class="{% if active_tab == 'settings-list' %} active{% endif %}">
                        <a href="{{ reports_settings_list_url }}">
                            <i class="fa fa-sliders"></i>
                            <span>Settings</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        {% block container %}
            <div class="content-wrapper">
                <div class="container" style="min-height:700px">
                    {% block content %}{% endblock %}
                </div>
            </div>
        {% endblock container %}
    </div>
    {% endblock nav %}
{% endblock maincontent %}